version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "python manage.py runserver & tail -f /dev/null"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
volumes:
  db_data: